language: bash
dist: bionic

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - PATH: /snap/bin:$PATH

addons:
  snaps:
    - name: snapcraft
      channel: stable
      classic: true
    - name: http
    - name: lxd
      channel: stable

install:
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - sudo adduser "$USER" lxd
script:
  - snapcraft --use-lxd
after_failure:
  - http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
