name: mumble
summary: Mumble is an open source, low-latency, high quality voice chat software. # 79 char long summary
description: |
  Mumble is a voice chat application for groups. While it can be used for any
  kind   of activity, it is primarily intended for gaming. It can be compared
  to programs like Ventrilo or TeamSpeak. People tend to simplify things, so
  when they talk   about Mumble they either talk about "Mumble" the client
  application or about "Mumble & Murmur" the whole voice chat application suite.
adopt-info: mumble
base: core18

grade: stable
confinement: strict

apps:
  mumble:
    command: bin/mumble
    command-chain: [bin/desktop-launch]
    environment:
      ALSA_CONFIG_PATH: $SNAP/etc/alsa.conf
    plugs:
      - audio-playback
      - audio-record
      - desktop
      - desktop-legacy
      - home
      - jack1
      - network
      - network-manager
      - opengl
      - unity7
      - wayland
      - x11

parts:
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - qtwayland5
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
  mumble:
    after: [desktop-qt5]
    plugin: cmake
    source: https://github.com/mumble-voip/mumble.git
    source-branch: "master"
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -Dsymbols=ON
      - -Dserver=OFF
      - -Doverlay-xcompile=OFF
      - -DNO_UPDATE_CHECK=1
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | tail -n 1)"
      last_released_tag="$(snap info mumble | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags)"
      git submodule update --init --recursive
    build-snaps: [cmake]
    build-packages:
      - libasound2-dev
      - libavahi-compat-libdnssd-dev
      - libboost-dev
      - libcap-dev
      - libg15daemon-client-dev
      - libgl1-mesa-dev
      - libgrpc++-dev
      - libjack-dev
      - libogg-dev
      - libpoco-dev
      - libprotobuf-dev
      - libprotoc-dev
      - libpulse-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - libsndfile1-dev
      - libspeechd-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libssl-dev
      - libxi-dev
      - libzeroc-ice-dev
      - protobuf-compiler
      - qt5-default
      - qttools5-dev
      - qttools5-dev-tools
      - qttranslations5-l10n
      - zeroc-ice-compilers
      - zeroc-ice-slice
    stage-packages:
      - jackd1
      - libasyncns0
      - libavahi-compat-libdnssd1
      - libflac8
      - libg15daemon-client1
      - libgl1-mesa-glx
      - libglu1-mesa
      - libgtk2.0-0
      - libogg0
      - libpocofoundation50
      - libpocoxml50
      - libpocozip50
      - libprotobuf10
      - libpulse0
      - libqt5sql5-sqlite
      - libqt5xml5
      - libsndfile1
      - libspeechd2
      - libspeex1
      - libspeexdsp1
      - libthai-data
      - libvorbis0a
      - libvorbisenc2
